### PR TITLE
Add edges to GraphAnalyitics

### PR DESCRIPTION
**Pull request by dhaneshnm**
- Show edges.
- Change colors.
- Change display panel to collapsable panel.

Fixes   BlueBrain/nexus/issues/3026
Fixes   BlueBrain/nexus/issues/3027

## Description

Changes style Graph Analytics tab and Add edges to the graph.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added necessary unit and integration tests.
- [x] I have added screenshots (if applicable), in the comment section.

### CODE REVIEW

**Comment by dhaneshnm** [comment]
Screenshot 2022-01-24 at 09 27 17

**Comment by dhaneshnm** [comment]
Screenshot 2022-01-24 at 09 27 09

**Comment by dhaneshnm** [comment]
Screenshot 2022-01-24 at 08 32 27

**Comment by dhaneshnm** [comment]
Screenshot 2022-01-24 at 08 32 19

**Review by nicwells — APPROVED** [review]

**Pull request merged**
