### PR TITLE
New README proposal

### PR DESCRIPTION
**Pull request by bilalesi**
Fixes #https://github.com/BlueBrain/nexus/issues/4321

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added necessary unit and integration tests.
- [ ] I have added screenshots (if applicable), in the comment section.

### CODE REVIEW

**Review by Dinika — COMMENTED** [review]
Questions:

- Why is this file called `NewReadme.md`? Shouldn't we just change the existing README? 
- In the current README, the development guidelines is just a link to a separate file `development.md`. Should we follow the same pattern here and put all the sections after `contributing` in a separate file?

**Review by Dinika — APPROVED** [review]

**Comment by bilalesi** [comment]
@Dinika this is a draft, we will do a meeting to discuss what's the best way on how to organize the readme and what we should include or not

**Comment by danburonline** [comment]
**Question:** We have a wiki on our Nexus-web repository. Should we only add all our repository-specific documentation into the README, similar to how [Cal.com](https://github.com/calcom/cal.com) did it?

**Comment by danburonline** [comment]
**🔔 Just as a reminder:** We should add the information from [the Wiki of this repository](https://github.com/BlueBrain/nexus-web/wiki) to the new README, and then remove the Wiki tab in the settings. It's quite confusing to have the external page <https://bluebrainnexus.io/docs/fusion>, the README, and the Wiki all together.

**Pull request closed without merging**
